substitutions:
  name: "gg-voice-tdm"
  friendly_name: "gg-voice-tdm"
  model_2: https://raw.githubusercontent.com/arturgadelshin/wakeword_miluy_dom_2/refs/heads/main/stream_state_internal_quant_1_17_lh.json    
  id_2: muliy_dom2_1_17_lh
  external_media_player_id: speaker_media_player_id

esphome:
  name: ${name}
  min_version: 2023.11.0
  platformio_options:
    board_build.flash_mode: qio
  on_boot:
    - priority: -100
      then:
        - light.turn_on:
            id: led_ring
            effect: power
        - delay: 1s
        - light.turn_on:
            id: led_ring
            effect: Working
            red: 0%
            blue: 100%
            green: 0%
        - wait_until:
            condition:
              api.connected:
        - delay: 1.5s
        - micro_wake_word.start:
        - script.execute: reset_led

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "30"

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG
  baud_rate: 115200

api:
  reboot_timeout: 3min

ota:
  - platform: esphome

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: "$ IP Address"

ethernet:
  type: W5500
  clk_pin: GPIO13
  mosi_pin: GPIO11
  miso_pin: GPIO12
  cs_pin: GPIO14
  interrupt_pin: GPIO10
  reset_pin: GPIO9
  clock_speed: 14Mhz

i2c:
  id: bus_i2c
  sda: GPIO8
  scl: GPIO18
  scan: true
  frequency: 100kHz

# === TDM ES7210 - 4 channel microphone ===
es7210_tdm:
  id: es7210_adc
  i2c_id: bus_i2c
  bits_per_sample: 32bit
  sample_rate: 16000
  mic_gain: "24db"

i2s_tdm_audio:
  - id: tdm_mic_bus
    i2s_lrclk_pin: GPIO45
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO2

microphone:
  - platform: i2s_tdm_audio
    id: tdm_mic
    i2s_tdm_audio_id: tdm_mic_bus
    i2s_din_pin: GPIO16
    sample_rate: 16000
    bits_per_sample: 32bit
    correct_dc_offset: false
    debug: false

# === ES8311 speaker ===
audio_dac:
  - platform: es8311
    id: es8311_dac
    use_mclk: true
    address: 0x18
    bits_per_sample: 16bit
    sample_rate: 48000
    i2c_id: bus_i2c

i2s_audio:
  - id: codec
    i2s_lrclk_pin: GPIO41
    i2s_bclk_pin: GPIO40
    i2s_mclk_pin: GPIO42

speaker:
  - platform: i2s_audio
    id: external_speaker
    dac_type: external
    i2s_audio_id: codec
    i2s_dout_pin: GPIO39
    sample_rate: 48000
    bits_per_sample: 16bit
    channel: mono
    buffer_duration: 100ms
    audio_dac: es8311_dac

  - id: mixing_speaker
    platform: mixer
    output_speaker: external_speaker
    source_speakers:
      - id: announcement_mixing_input
      - id: media_mixing_input

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000

media_player:
  - platform: speaker
    name: "Speaker Media Player"
    id: speaker_media_player_id
    internal: False
    volume_increment: 0.05
    volume_min: 0.4
    volume_max: 0.85
    buffer_size: 100000
    task_stack_in_psram: true

    announcement_pipeline:
      speaker: announcement_resampling_speaker
      num_channels: 2
      format: MP3
      sample_rate: 48000

    media_pipeline:
      speaker: media_resampling_speaker
      num_channels: 2
      format: MP3
      sample_rate: 48000

    files:
      - id: wake_sound_file
        file: https://github.com/arturgadelshin/sound_ai_home/raw/main/sounds/awake_2.mp3
      - id: error_sound_file
        file: https://github.com/arturgadelshin/sound_ai_home/raw/main/sounds/error_3.mp3

    on_idle:
      - micro_wake_word.start:

# === MICRO WAKE WORD ===
micro_wake_word:
  id: mww
  stop_after_detection: true
  microphone:
    channels: 0
    gain_factor: 1
  models:
    - model: ${model_2}
      id: ${id_2}
  on_wake_word_detected:
    - logger.log: "Wake word detected"
    - if:
        condition:
          or:
            - voice_assistant.is_running:
            - media_player.is_announcing:
        then:
          - logger.log: "Ignoring wake word - busy"
        else:
          - logger.log: "Starting voice assistant"
          - if:
              condition:
                media_player.is_announcing:
                  id: ${external_media_player_id}
              then:
                - media_player.stop:
                    announcement: true
                    id: ${external_media_player_id}
              else:
                - media_player.speaker.play_on_device_media_file:
                    media_file: wake_sound_file
                    announcement: true
                - wait_until:
                    not:
                      - media_player.is_announcing:
                          id: ${external_media_player_id}
                - delay: 300ms
                - voice_assistant.start:
                    wake_word: !lambda return wake_word;

# === VOICE ASSISTANT ===
voice_assistant:
  id: voice_asst
  media_player: speaker_media_player_id
  microphone:
    channels: 0
    gain_factor: 5
  micro_wake_word: mww
  noise_suppression_level: 1
  volume_multiplier: 1.0

  on_listening:
    - light.turn_on:
        id: led_ring
        blue: 80%
        red: 80%
        green: 80%
        brightness: 80%
        effect: wakeword

  on_end:
    - micro_wake_word.stop
    - delay: 200ms
    - micro_wake_word.start
    - script.execute: reset_led

  on_error:
    - light.turn_on:
        id: led_ring
        blue: 0%
        red: 100%
        green: 0%
        brightness: 80%
        effect: none
    - media_player.speaker.play_on_device_media_file:
        media_file: error_sound_file
        announcement: true
    - micro_wake_word.stop
    - delay: 200ms
    - micro_wake_word.start
    - script.execute: reset_led

script:
  - id: reset_led
    mode: restart
    then:
      - delay: 50ms
      - if:
          condition:
            switch.is_on: night_mode
          then:
            - light.turn_on:
                id: led_ring
                blue: 100%
                red: 0%
                green: 0%
                brightness: 30%
                effect: none
          else:
            - light.turn_on:
                id: led_ring
                blue: 100%
                red: 0%
                green: 0%
                brightness: 80%
                effect: none

# === SWITCHES ===
switch:
  - platform: template
    name: Night Mode Switch
    id: night_mode
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    on_turn_on:
      - script.execute: reset_led
    on_turn_off:
      - script.execute: reset_led

  - platform: gpio
    pin: GPIO15
    inverted: False
    restore_mode: RESTORE_DEFAULT_OFF
    name: "Relay Lift"
    id: relay_status

# === LIGHT ===
light:
  - platform: esp32_rmt_led_strip
    id: led_ring
    name: "${friendly_name} Light"
    pin: GPIO38
    num_leds: 24
    rgb_order: GRB
    chipset: ws2812
    default_transition_length: 0s
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - addressable_twinkle:
          name: "Working"
          twinkle_probability: 80%
          progress_interval: 50ms
      - addressable_color_wipe:
          name: "Wakeword"
          colors:
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 12
          add_led_interval: 40ms
          reverse: false
      - addressable_color_wipe:
          name: "Power"
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 12
          add_led_interval: 50ms
          reverse: false

# === SELECT ===
select:
  - platform: template
    name: "Sensitivity Muliy_dom_2"
    optimistic: true
    initial_option: 0.70 sensitive
    restore_value: true
    entity_category: config
    options:
      - 0.01 sensitive
      - 0.02 sensitive
      - 0.03 sensitive
      - 0.04 sensitive
      - 0.05 sensitive
      - 0.10 sensitive
      - 0.20 sensitive
      - 0.30 sensitive
      - 0.40 sensitive
      - 0.50 sensitive
      - 0.55 sensitive
      - 0.60 sensitive
      - 0.65 sensitive
      - 0.70 sensitive
      - 0.75 sensitive
      - 0.80 sensitive
      - 0.85 sensitive
      - 0.90 sensitive
      - 0.95 sensitive
      - 0.98 sensitive
    on_value:
      lambda: |-
        if (x == "0.01 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(3);
        } else if (x == "0.02 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(6);
        } else if (x == "0.03 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(9);
        } else if (x == "0.04 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(11);
        } else if (x == "0.05 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(13);
        } else if (x == "0.10 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(26);
        } else if (x == "0.20 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(51);
        } else if (x == "0.30 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(76);
        } else if (x == "0.40 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(102);
        } else if (x == "0.50 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(128);
        } else if (x == "0.55 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(140);
        } else if (x == "0.60 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(153);
        } else if (x == "0.65 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(166);
        } else if (x == "0.70 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(179);
        } else if (x == "0.75 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(191);
        } else if (x == "0.80 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(204);
        } else if (x == "0.85 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(217);
        } else if (x == "0.90 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(230);
        } else if (x == "0.95 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(242);
        } else if (x == "0.98 sensitive") {
          id(muliy_dom2_1_17_lh).set_probability_cutoff(250);
        }

button:
  - platform: restart
    name: "Restart module"
